// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/2fa/status',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getTwoFactorStatus',
    summary: 'Get two-factor authentication status',
    description:
      'Returns whether two-factor authentication is enabled, configured, or required for the current user, including the reason it is required.',
    tags: ['Two-factor authentication'],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    isEnabled: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication is enabled.',
                    },
                    isRequired: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication is required for this user.',
                    },
                    requiredReason: {
                      type: 'null',
                      description: 'Reason two-factor authentication is required.',
                    },
                    isConfigured: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication has been configured.',
                    },
                    globalRequired: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication is required for all users.',
                    },
                  },
                  required: [
                    'isEnabled',
                    'isRequired',
                    'requiredReason',
                    'isConfigured',
                    'globalRequired',
                  ],
                },
                {
                  type: 'object',
                  properties: {
                    isEnabled: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication is enabled.',
                    },
                    isRequired: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication is required for this user.',
                    },
                    requiredReason: {
                      type: 'string',
                      description: 'Reason two-factor authentication is required.',
                    },
                    isConfigured: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication has been configured.',
                    },
                    globalRequired: {
                      type: 'boolean',
                      description: 'Whether two-factor authentication is required for all users.',
                    },
                  },
                  required: [
                    'isEnabled',
                    'isRequired',
                    'requiredReason',
                    'isConfigured',
                    'globalRequired',
                  ],
                },
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
