// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/share/id/{shareId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteShare',
    summary: 'Delete a share',
    description:
      'Deletes the specified share after checking permission to delete shares for its resource.',
    tags: ['Shares'],
    parameters: [
      {
        name: 'shareId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'Identifier used to access a shared resource.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/share/id/{shareId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getShare',
    summary: 'Get a share',
    description:
      "Returns a share's configuration by its ID after checking access to the shared resource.",
    tags: ['Shares'],
    parameters: [
      {
        name: 'shareId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'Identifier used to access a shared resource.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                slug: {
                  type: 'string',
                  description: 'URL slug used to access the resource.',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description: 'Configuration parameters for the resource.',
                },
                entityId: {
                  type: 'string',
                  description: 'ID of the resource being shared.',
                },
                shareType: {
                  type: 'number',
                  description: 'Type of resource made available by the share.',
                },
              },
              required: [
                'id',
                'createdAt',
                'updatedAt',
                'name',
                'slug',
                'parameters',
                'entityId',
                'shareType',
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/share/id/{shareId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updateShare',
    summary: 'Update a share',
    description: "Updates the specified share's name, slug, and parameters.",
    tags: ['Shares'],
    parameters: [
      {
        name: 'shareId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'Identifier used to access a shared resource.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 200,
                description: 'Display name of the resource.',
              },
              slug: {
                description: 'URL slug used to access the resource.',
              },
              parameters: {
                description: 'Configuration parameters for the resource.',
              },
            },
            required: ['name', 'slug', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
