// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/segments',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteSegments',
    summary: 'List website segments and cohorts',
    description:
      'Returns saved segments or cohorts for the website, filtered by the requested type and search text.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'type',
        in: 'query',
        required: true,
        schema: {
          type: 'string',
          enum: ['segment', 'cohort'],
        },
        description: 'Type of resource or analytics dimension to return.',
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Search text used to filter results.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  description: 'Data returned by the operation.',
                },
                count: {
                  description: 'Number of matching records.',
                },
                page: {
                  type: 'number',
                  description: 'Page number, starting at 1.',
                },
                pageSize: {
                  type: 'number',
                  description: 'Number of results per page.',
                },
                orderBy: {
                  type: 'string',
                  description: 'Field to sort the results by.',
                },
                search: {
                  type: 'string',
                  description: 'Search text used to filter results.',
                },
              },
              required: ['data', 'count', 'page', 'pageSize', 'orderBy', 'search'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/websites/{websiteId}/segments',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createWebsiteSegment',
    summary: 'Create a website segment or cohort',
    description:
      'Saves a named segment or cohort with its type and filter parameters for the website.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {},
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
