// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/record',
  audience: 'collect',
  auth: 'none',
  operation: {
    operationId: 'record',
    summary: 'Send session recordings or heatmap data',
    description:
      'Stores session replay events or heatmap clicks and scrolls for a website, using a valid tracking cache token to identify the session and visit.',
    tags: ['Collection'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            anyOf: [
              {
                type: 'object',
                properties: {
                  type: {
                    const: 'record',
                  },
                  payload: {
                    type: 'object',
                    properties: {
                      website: {
                        type: 'string',
                        format: 'uuid',
                      },
                      events: {
                        type: 'array',
                        items: {},
                        maxItems: 200,
                      },
                      timestamp: {
                        type: 'integer',
                      },
                    },
                    required: ['website', 'events'],
                  },
                },
                required: ['type', 'payload'],
              },
              {
                type: 'object',
                properties: {
                  type: {
                    const: 'heatmap',
                  },
                  payload: {
                    type: 'object',
                    properties: {
                      website: {
                        type: 'string',
                        format: 'uuid',
                      },
                      events: {
                        type: 'array',
                        items: {
                          anyOf: [
                            {
                              type: 'object',
                              properties: {
                                type: {
                                  const: 'click',
                                },
                                url: {
                                  type: 'string',
                                  description: 'URL associated with the resource.',
                                },
                                x: {
                                  minimum: 0,
                                  maximum: 10000000,
                                },
                                y: {
                                  minimum: 0,
                                  maximum: 10000000,
                                },
                                pageX: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Horizontal position on the page in pixels.',
                                },
                                pageY: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Vertical position on the page in pixels.',
                                },
                                pageW: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Page width in pixels.',
                                },
                                pageH: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Page height in pixels.',
                                },
                                viewportW: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Viewport width in pixels.',
                                },
                                viewportH: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Viewport height in pixels.',
                                },
                                timestamp: {
                                  minimum: 0,
                                },
                              },
                              required: ['type', 'url'],
                            },
                            {
                              type: 'object',
                              properties: {
                                type: {
                                  const: 'scroll',
                                },
                                url: {
                                  type: 'string',
                                  description: 'URL associated with the resource.',
                                },
                                scrollPct: {
                                  minimum: 0,
                                  maximum: 100,
                                },
                                pageW: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Page width in pixels.',
                                },
                                pageH: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Page height in pixels.',
                                },
                                viewportW: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Viewport width in pixels.',
                                },
                                viewportH: {
                                  minimum: 0,
                                  maximum: 10000000,
                                  description: 'Viewport height in pixels.',
                                },
                                timestamp: {
                                  minimum: 0,
                                },
                              },
                              required: ['type', 'url'],
                            },
                          ],
                        },
                        maxItems: 200,
                      },
                      timestamp: {
                        type: 'integer',
                      },
                    },
                    required: ['website', 'events'],
                  },
                },
                required: ['type', 'payload'],
              },
            ],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'text/plain': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    ok: {
                      type: 'boolean',
                      description: 'Whether the operation succeeded.',
                    },
                  },
                  required: ['ok'],
                },
                {
                  type: 'object',
                  properties: {
                    ok: {
                      type: 'boolean',
                      description: 'Whether the operation succeeded.',
                    },
                    reason: {
                      type: 'string',
                    },
                  },
                  required: ['ok', 'reason'],
                },
              ],
            },
          },
        },
      },
      '204': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'text/plain': {
            schema: {
              type: 'string',
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '403': {
        description: 'Forbidden.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Forbidden.',
                code: 'forbidden',
                status: 403,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '500': {
        description: 'Server error.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Server error.',
                code: 'server-error',
                status: 500,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
