// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/replays/{replayId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteReplay',
    summary: 'Get a session replay recording',
    description:
      'Returns the merged recording events, session details, and event and chunk counts for a replay, with optional stopping points by timestamp, chunk, or event index.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'replayId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the session replay.',
      },
      {
        name: 'until',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 0,
        },
      },
      {
        name: 'chunkIndex',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 0,
          maximum: 10000000,
        },
      },
      {
        name: 'eventIndex',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 0,
          maximum: 10000,
        },
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                sessionId: {
                  type: 'string',
                  description: 'ID of the visitor session.',
                },
                events: {
                  type: 'array',
                  items: {},
                },
                startedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the recording started.',
                },
                endedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the recording ended.',
                },
                eventCount: {
                  type: 'number',
                  description: 'Number of recorded replay events.',
                },
                chunkCount: {
                  type: 'number',
                  description: 'Number of stored recording chunks.',
                },
              },
              required: ['sessionId', 'events', 'startedAt', 'endedAt', 'eventCount', 'chunkCount'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
