// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/pixels',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getPixels',
    summary: 'List my tracking pixels',
    description:
      "Returns a paginated list of the current user's tracking pixels, with search and sorting options.",
    tags: ['Pixels'],
    parameters: [
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Page number, starting at 1.',
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Number of results per page.',
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Maximum number of results to include.',
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Search text used to filter results.',
      },
      {
        name: 'orderBy',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Field to sort the results by.',
      },
      {
        name: 'sortDescending',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['true', 'false'],
        },
        description: 'Whether to sort results in descending order.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  description: 'Data returned by the operation.',
                },
                count: {
                  description: 'Number of matching records.',
                },
                page: {
                  type: 'number',
                  description: 'Page number, starting at 1.',
                },
                pageSize: {
                  type: 'number',
                  description: 'Number of results per page.',
                },
                orderBy: {
                  type: 'string',
                  description: 'Field to sort the results by.',
                },
                search: {
                  type: 'string',
                  description: 'Search text used to filter results.',
                },
              },
              required: ['data', 'count', 'page', 'pageSize', 'orderBy', 'search'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/pixels',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createPixel',
    summary: 'Create a tracking pixel',
    description: 'Creates a tracking pixel with a name and slug, optionally assigned to a team.',
    tags: ['Pixels'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 100,
                description: 'Display name of the resource.',
              },
              slug: {
                description: 'URL slug used to access the resource.',
              },
              teamId: {
                anyOf: [
                  {
                    type: 'string',
                    format: 'uuid',
                  },
                  {
                    type: 'null',
                  },
                ],
                description: 'ID of the associated team.',
              },
              id: {
                anyOf: [
                  {
                    type: 'string',
                    format: 'uuid',
                  },
                  {
                    type: 'null',
                  },
                ],
                description: 'Unique identifier of the resource.',
              },
            },
            required: ['name', 'slug'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
