// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/dashboard',
  audience: 'internal',
  auth: 'bearer',
  operation: {
    operationId: 'getDashboard',
    summary: 'Get my dashboard',
    description: "Returns the current user's personal dashboard board and its configuration.",
    tags: ['Dashboard'],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Dashboard board ID, equal to the owning user ID.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the user who owns the dashboard.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the dashboard.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team, if any.',
                },
                type: {
                  type: 'string',
                  description: 'Board type used for the dashboard.',
                },
                description: {
                  type: 'string',
                  description: 'Description of the dashboard.',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description:
                    'Dashboard configuration, including components, layout, and saved reports.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'name',
                'teamId',
                'type',
                'description',
                'parameters',
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/dashboard',
  audience: 'internal',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'postDashboard',
    summary: 'Save my dashboard',
    description:
      "Creates or updates the current user's personal dashboard with the supplied name, description, and configuration.",
    tags: ['Dashboard'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                maximum: 100,
                description: 'Display name of the dashboard.',
              },
              description: {
                type: 'string',
                maxLength: 500,
                description: 'Description of the dashboard.',
              },
              parameters: {
                description:
                  'Dashboard configuration, including components, layout, and saved reports.',
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Dashboard board ID, equal to the owning user ID.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the user who owns the dashboard.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the dashboard.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team, if any.',
                },
                type: {
                  type: 'string',
                  description: 'Board type used for the dashboard.',
                },
                description: {
                  type: 'string',
                  description: 'Description of the dashboard.',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description:
                    'Dashboard configuration, including components, layout, and saved reports.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'name',
                'teamId',
                'type',
                'description',
                'parameters',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
