// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/websites/{websiteId}/transfer',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'transferWebsite',
    summary: 'Transfer website ownership',
    description:
      'Transfers the specified website to another user or team after checking permission for the destination.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              userId: {
                type: 'string',
                format: 'uuid',
                description: 'ID of the associated user.',
              },
              teamId: {
                type: 'string',
                format: 'uuid',
                description: 'ID of the associated team.',
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                deletedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was deleted, if applicable.',
                },
                createdBy: {
                  type: 'string',
                  description: 'ID of the user who created the resource.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                domain: {
                  type: 'string',
                  description: 'Domain name associated with the resource.',
                },
                resetAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the website analytics were last reset.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team.',
                },
                recorderEnabled: {
                  type: 'boolean',
                  description: 'Whether recording is enabled for the website.',
                },
                replayConfig: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description: 'Session replay and heatmap recording configuration.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'deletedAt',
                'createdBy',
                'name',
                'domain',
                'resetAt',
                'teamId',
                'recorderEnabled',
                'replayConfig',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
