// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/users/{userId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteUser',
    summary: 'Delete a user',
    description:
      'Deletes the specified user account. The current user cannot delete their own account through this operation.',
    tags: ['Users'],
    parameters: [
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/users/{userId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getUser',
    summary: 'Get a user',
    description:
      'Returns details for the specified user account when the caller has permission to view it.',
    tags: ['Users'],
    parameters: [
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                username: {
                  type: 'string',
                  description: 'Username of the account.',
                },
                role: {
                  type: 'string',
                  description: 'Permission role assigned to the user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                twoFactorRequired: {
                  type: 'boolean',
                  description: 'Whether two-factor authentication is required.',
                },
              },
              required: ['id', 'username', 'role', 'createdAt', 'twoFactorRequired'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/users/{userId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updateUser',
    summary: 'Update a user',
    description: "Updates a user's password. Administrators can also change the username and role.",
    tags: ['Users'],
    parameters: [
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              username: {
                minimum: 1,
                maximum: 255,
                description: 'Username of the account.',
              },
              password: {
                description: 'Password used to authenticate the account.',
              },
              role: {
                type: 'string',
                enum: ['admin', 'user', 'view-only'],
                description: 'Permission role assigned to the user.',
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '403': {
        description: 'Forbidden.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Forbidden.',
                code: 'forbidden',
                status: 403,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
