// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/realtime/{websiteId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getRealtime',
    summary: 'Get real-time website activity',
    description:
      'Returns recent website activity and visitor data for the real-time view, applying the supplied filters.',
    tags: ['Realtime'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description:
          'IANA time zone used to interpret dates and group results, for example America/New_York.',
      },
      {
        name: 'unit',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Time interval used to group results: minute, hour, day, month, or year.',
      },
      {
        name: 'path',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page URL path.',
      },
      {
        name: 'referrer',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by referring URL.',
      },
      {
        name: 'title',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page title.',
      },
      {
        name: 'query',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page URL query string.',
      },
      {
        name: 'os',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Operating system used by the visitor.',
      },
      {
        name: 'browser',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Browser used by the visitor.',
      },
      {
        name: 'device',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Device category used by the visitor.',
      },
      {
        name: 'country',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Country code of the visitor.',
      },
      {
        name: 'region',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Region or subdivision of the visitor.',
      },
      {
        name: 'city',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'City of the visitor.',
      },
      {
        name: 'tag',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Tag attached to the tracked activity.',
      },
      {
        name: 'hostname',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Hostname on which the activity occurred.',
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Custom identifier assigned to the visitor.',
      },
      {
        name: 'language',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Preferred language reported by the visitor browser.',
      },
      {
        name: 'event',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by custom event name.',
      },
      {
        name: 'utmSource',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign source.',
      },
      {
        name: 'utmMedium',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign medium.',
      },
      {
        name: 'utmCampaign',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign name.',
      },
      {
        name: 'utmContent',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign content.',
      },
      {
        name: 'utmTerm',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign search term.',
      },
      {
        name: 'excludeBounce',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Set a non-empty value to exclude visits with only one pageview.',
      },
      {
        name: 'segment',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
        description: 'ID of a saved segment used to filter results.',
      },
      {
        name: 'cohort',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
        description: 'ID of a saved cohort used to filter visitors.',
      },
      {
        name: 'eventType',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Event type: 1 for a pageview or 2 for a custom event.',
      },
      {
        name: 'match',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['all', 'any'],
        },
        description: 'Whether records must match all filters or any filter.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                countries: {
                  type: 'object',
                  properties: {},
                  additionalProperties: {
                    type: 'number',
                  },
                },
                events: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      __type: {
                        anyOf: [
                          {
                            const: 'event',
                          },
                          {
                            const: 'session',
                          },
                          {
                            const: 'pageview',
                          },
                        ],
                      },
                      sessionId: {
                        type: 'string',
                        description: 'ID of the visitor session.',
                      },
                      eventName: {
                        type: 'string',
                        description: 'Name of the custom event.',
                      },
                      createdAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                        description: 'Date and time the record was created.',
                      },
                      browser: {
                        type: 'string',
                        description: 'Browser used by the visitor.',
                      },
                      os: {
                        type: 'string',
                        description: 'Operating system used by the visitor.',
                      },
                      device: {
                        type: 'string',
                        description: 'Device category used by the visitor.',
                      },
                      country: {
                        type: 'string',
                        description: 'Country code of the visitor.',
                      },
                      urlPath: {
                        type: 'string',
                        description: 'Path portion of the page URL.',
                      },
                      referrerDomain: {
                        type: 'string',
                        description: 'Domain of the referring page.',
                      },
                      hostname: {
                        type: 'string',
                        description: 'Hostname on which the activity occurred.',
                      },
                    },
                    required: [
                      '__type',
                      'sessionId',
                      'eventName',
                      'createdAt',
                      'browser',
                      'os',
                      'device',
                      'country',
                      'urlPath',
                      'referrerDomain',
                      'hostname',
                    ],
                  },
                },
                referrers: {
                  type: 'object',
                  properties: {},
                  additionalProperties: {
                    type: 'number',
                  },
                },
                timestamp: {
                  type: 'number',
                },
                series: {
                  type: 'object',
                  properties: {
                    views: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          x: {
                            type: 'string',
                          },
                          t: {
                            type: 'string',
                          },
                          y: {
                            type: 'number',
                          },
                        },
                        required: ['x', 't', 'y'],
                      },
                      description: 'Pageview counts for the selected period.',
                    },
                    visitors: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          x: {
                            type: 'string',
                          },
                          t: {
                            type: 'string',
                          },
                          y: {
                            type: 'number',
                          },
                        },
                        required: ['x', 't', 'y'],
                      },
                      description: 'Unique visitor counts for the selected period.',
                    },
                  },
                  required: ['views', 'visitors'],
                },
                totals: {
                  type: 'object',
                  properties: {
                    views: {
                      type: 'number',
                      description: 'Pageview counts for the selected period.',
                    },
                    visitors: {
                      type: 'number',
                      description: 'Unique visitor counts for the selected period.',
                    },
                    events: {
                      type: 'number',
                    },
                    countries: {
                      type: 'number',
                    },
                  },
                  required: ['views', 'visitors', 'events', 'countries'],
                },
                urls: {
                  type: 'object',
                  properties: {},
                  additionalProperties: {
                    type: 'number',
                  },
                },
              },
              required: [
                'countries',
                'events',
                'referrers',
                'timestamp',
                'series',
                'totals',
                'urls',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
