// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/sessions/{sessionId}/replays',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteSessionReplays',
    summary: "List a visitor's session replays",
    description:
      'Returns a paginated, searchable list of recordings for the specified website session.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'sessionId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the visitor session.',
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
        description: 'Start of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
        description: 'End of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'startDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
        description: 'Start of the date range as an ISO 8601 date or date-time.',
      },
      {
        name: 'endDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
        description: 'End of the date range as an ISO 8601 date or date-time.',
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description:
          'IANA time zone used to interpret dates and group results, for example America/New_York.',
      },
      {
        name: 'unit',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Time interval used to group results: minute, hour, day, month, or year.',
      },
      {
        name: 'compare',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['prev', 'yoy'],
        },
        description:
          'Comparison period: prev for the previous period or yoy for the same period last year.',
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Page number, starting at 1.',
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Number of results per page.',
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Maximum number of results to include.',
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Search text used to filter results.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                        description: 'Unique identifier of the resource.',
                      },
                      sessionId: {
                        type: 'string',
                        description: 'ID of the visitor session.',
                      },
                      websiteId: {
                        type: 'string',
                        description: 'ID of the website.',
                      },
                      browser: {
                        type: 'string',
                        description: 'Browser used by the visitor.',
                      },
                      os: {
                        type: 'string',
                        description: 'Operating system used by the visitor.',
                      },
                      device: {
                        type: 'string',
                        description: 'Device category used by the visitor.',
                      },
                      country: {
                        type: 'string',
                        description: 'Country code of the visitor.',
                      },
                      city: {
                        type: 'string',
                        description: 'City of the visitor.',
                      },
                      eventCount: {
                        type: 'number',
                        description: 'Number of recorded replay events.',
                      },
                      chunkCount: {
                        type: 'number',
                        description: 'Number of stored recording chunks.',
                      },
                      startedAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                        description: 'Date and time the recording started.',
                      },
                      endedAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                        description: 'Date and time the recording ended.',
                      },
                      duration: {
                        type: 'number',
                        description: 'Replay duration in milliseconds.',
                      },
                      createdAt: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'string',
                            format: 'date-time',
                          },
                        ],
                        description: 'Date and time the record was created.',
                      },
                    },
                    required: [
                      'id',
                      'sessionId',
                      'websiteId',
                      'browser',
                      'os',
                      'device',
                      'country',
                      'city',
                      'eventCount',
                      'chunkCount',
                      'startedAt',
                      'endedAt',
                      'duration',
                      'createdAt',
                    ],
                  },
                  description: 'Data returned by the operation.',
                },
                count: {
                  type: 'number',
                  description: 'Number of matching records.',
                },
                page: {
                  type: 'number',
                  description: 'Page number, starting at 1.',
                },
                pageSize: {
                  type: 'number',
                  description: 'Number of results per page.',
                },
                orderBy: {
                  type: 'string',
                  description: 'Field to sort the results by.',
                },
                sortDescending: {
                  type: 'boolean',
                  description: 'Whether to sort results in descending order.',
                },
                search: {
                  type: 'string',
                  description: 'Search text used to filter results.',
                },
                isCapped: {
                  type: 'boolean',
                  description: 'Whether the results were truncated by the maximum result limit.',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
