// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/event-data/{eventId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getEventDataById',
    summary: "Get an event's custom properties",
    description:
      'Returns the custom property records, data types, and values attached to a specific event.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'eventId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the event.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                    description: 'Unique identifier of the resource.',
                  },
                  createdAt: {
                    type: 'string',
                    format: 'date-time',
                    description: 'Date and time the record was created.',
                  },
                  websiteId: {
                    type: 'string',
                    description: 'ID of the website.',
                  },
                  websiteEventId: {
                    type: 'string',
                    description: 'ID of the website event.',
                  },
                  dataKey: {
                    type: 'string',
                    description: 'Name of the custom property.',
                  },
                  stringValue: {
                    type: 'string',
                    description: 'Custom property value stored as a string.',
                  },
                  numberValue: {
                    type: 'object',
                    properties: {
                      d: {
                        type: 'array',
                        items: {
                          type: 'number',
                        },
                      },
                      e: {
                        type: 'number',
                      },
                      s: {
                        type: 'number',
                      },
                    },
                    required: ['d', 'e', 's'],
                    description: 'Custom property value stored as a number.',
                  },
                  dateValue: {
                    type: 'string',
                    format: 'date-time',
                    description: 'Custom property value stored as a date-time.',
                  },
                  dataType: {
                    type: 'number',
                    description: 'Data type of the custom property.',
                  },
                },
                required: [
                  'id',
                  'createdAt',
                  'websiteId',
                  'websiteEventId',
                  'dataKey',
                  'stringValue',
                  'numberValue',
                  'dateValue',
                  'dataType',
                ],
              },
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
