// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/me/api-keys',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getMyApiKeys',
    summary: 'List my API keys',
    description:
      "Returns metadata for the current user's API keys. Available on self-hosted installations.",
    tags: ['Account'],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                    description: 'Unique identifier of the resource.',
                  },
                  createdAt: {
                    type: 'string',
                    format: 'date-time',
                    description: 'Date and time the record was created.',
                  },
                  name: {
                    type: 'string',
                    description: 'Display name of the resource.',
                  },
                  keyPrefix: {
                    type: 'string',
                    description: 'Visible prefix used to identify an API key.',
                  },
                  lastUsedAt: {
                    type: 'string',
                    format: 'date-time',
                    description: 'Date and time the credential was last used.',
                  },
                },
                required: ['id', 'createdAt', 'name', 'keyPrefix', 'lastUsedAt'],
              },
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/me/api-keys',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createMyApiKey',
    summary: 'Create an API key',
    description:
      'Creates a named API key for the current user and returns its secret value. Available on self-hosted installations.',
    tags: ['Account'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 255,
                description: 'Display name of the resource.',
              },
            },
            required: ['name'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                key: {
                  type: 'string',
                },
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                keyPrefix: {
                  type: 'string',
                  description: 'Visible prefix used to identify an API key.',
                },
              },
              required: ['key', 'id', 'createdAt', 'name', 'keyPrefix'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
