// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/share/{slug}',
  audience: 'public',
  auth: 'none',
  operation: {
    operationId: 'getShareBySlug',
    summary: 'Open a share by its slug',
    description:
      'Resolves a public share slug and returns its resource references, parameters, and an access token scoped to the shared resources.',
    tags: ['Shares'],
    parameters: [
      {
        name: 'slug',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'URL slug used to access the resource.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {},
              additionalProperties: {},
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
