// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/events/stats',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteEventStats',
    summary: 'Get website event statistics',
    description:
      'Returns website event totals for the selected date range and filters, including totals for the comparison period.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'startAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
        description: 'Start of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'endAt',
        in: 'query',
        required: false,
        schema: {
          type: 'number',
        },
        description: 'End of the date range as a Unix timestamp in milliseconds.',
      },
      {
        name: 'startDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
        description: 'Start of the date range as an ISO 8601 date or date-time.',
      },
      {
        name: 'endDate',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'date-time',
        },
        description: 'End of the date range as an ISO 8601 date or date-time.',
      },
      {
        name: 'timezone',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description:
          'IANA time zone used to interpret dates and group results, for example America/New_York.',
      },
      {
        name: 'unit',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Time interval used to group results: minute, hour, day, month, or year.',
      },
      {
        name: 'compare',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['prev', 'yoy'],
        },
        description:
          'Comparison period: prev for the previous period or yoy for the same period last year.',
      },
      {
        name: 'path',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page URL path.',
      },
      {
        name: 'referrer',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by referring URL.',
      },
      {
        name: 'title',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page title.',
      },
      {
        name: 'query',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page URL query string.',
      },
      {
        name: 'os',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Operating system used by the visitor.',
      },
      {
        name: 'browser',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Browser used by the visitor.',
      },
      {
        name: 'device',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Device category used by the visitor.',
      },
      {
        name: 'country',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Country code of the visitor.',
      },
      {
        name: 'region',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Region or subdivision of the visitor.',
      },
      {
        name: 'city',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'City of the visitor.',
      },
      {
        name: 'tag',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Tag attached to the tracked activity.',
      },
      {
        name: 'hostname',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Hostname on which the activity occurred.',
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Custom identifier assigned to the visitor.',
      },
      {
        name: 'language',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Preferred language reported by the visitor browser.',
      },
      {
        name: 'event',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by custom event name.',
      },
      {
        name: 'utmSource',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign source.',
      },
      {
        name: 'utmMedium',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign medium.',
      },
      {
        name: 'utmCampaign',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign name.',
      },
      {
        name: 'utmContent',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign content.',
      },
      {
        name: 'utmTerm',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign search term.',
      },
      {
        name: 'excludeBounce',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Set a non-empty value to exclude visits with only one pageview.',
      },
      {
        name: 'segment',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
        description: 'ID of a saved segment used to filter results.',
      },
      {
        name: 'cohort',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
        description: 'ID of a saved cohort used to filter visitors.',
      },
      {
        name: 'eventType',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Event type: 1 for a pageview or 2 for a custom event.',
      },
      {
        name: 'match',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['all', 'any'],
        },
        description: 'Whether records must match all filters or any filter.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'object',
                  properties: {
                    comparison: {
                      type: 'array',
                      items: {
                        type: 'object',
                        properties: {
                          events: {
                            type: 'number',
                          },
                          visitors: {
                            type: 'number',
                            description: 'Unique visitor counts for the selected period.',
                          },
                          visits: {
                            type: 'number',
                            description: 'Visit counts for the selected period.',
                          },
                          uniqueEvents: {
                            type: 'number',
                            description: 'Number of unique events.',
                          },
                        },
                        required: ['events', 'visitors', 'visits', 'uniqueEvents'],
                      },
                      description: 'Analytics for the comparison period.',
                    },
                    length: {
                      type: 'number',
                    },
                  },
                  required: ['comparison', 'length'],
                  description: 'Data returned by the operation.',
                },
              },
              required: ['data'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
