// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/2fa/verify',
  audience: 'public',
  auth: 'none',
  operation: {
    operationId: 'verifyTwoFactor',
    summary: 'Complete two-factor sign-in',
    description:
      'Exchanges a partial sign-in token and a valid authenticator or backup code for a full authentication token and user details.',
    tags: ['Two-factor authentication'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            anyOf: [
              {
                type: 'object',
                properties: {
                  token: {
                    type: 'string',
                    minLength: 6,
                    maxLength: 6,
                  },
                },
                required: ['token'],
              },
              {
                type: 'object',
                properties: {
                  backupCode: {
                    type: 'string',
                    minLength: 1,
                    description: 'Single-use backup code for two-factor authentication.',
                  },
                },
                required: ['backupCode'],
              },
            ],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    error: {
                      type: 'object',
                      properties: {
                        code: {
                          type: 'string',
                        },
                        message: {
                          type: 'string',
                          description: 'Human-readable explanation of the result.',
                        },
                        lockedUntil: {
                          type: 'string',
                          format: 'date-time',
                          description:
                            'Time until which further authentication attempts are blocked.',
                        },
                      },
                      required: ['code', 'message', 'lockedUntil'],
                      description: 'Error details returned when the operation fails.',
                    },
                  },
                  required: ['error'],
                },
                {
                  type: 'object',
                  properties: {
                    token: {
                      type: 'string',
                    },
                    user: {
                      type: 'object',
                      properties: {
                        id: {
                          type: 'string',
                          description: 'Unique identifier of the resource.',
                        },
                        username: {
                          type: 'string',
                          description: 'Username of the account.',
                        },
                        role: {
                          type: 'string',
                          description: 'Permission role assigned to the user.',
                        },
                        createdAt: {
                          type: 'string',
                          format: 'date-time',
                          description: 'Date and time the record was created.',
                        },
                        isAdmin: {
                          type: 'boolean',
                          description: 'Whether the user has administrator privileges.',
                        },
                        teams: {
                          type: 'array',
                          items: {
                            type: 'object',
                            properties: {
                              id: {
                                type: 'string',
                                description: 'Unique identifier of the resource.',
                              },
                              logoUrl: {
                                type: 'string',
                                description: 'URL of the logo image.',
                              },
                              name: {
                                type: 'string',
                                description: 'Display name of the resource.',
                              },
                            },
                            required: ['id', 'logoUrl', 'name'],
                          },
                          description: 'Teams associated with the user.',
                        },
                      },
                      required: ['id', 'username', 'role', 'createdAt', 'isAdmin', 'teams'],
                      description: 'User associated with the resource.',
                    },
                  },
                  required: ['token', 'user'],
                },
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '429': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                error: {
                  type: 'object',
                  properties: {
                    code: {
                      type: 'string',
                    },
                    message: {
                      type: 'string',
                      description: 'Human-readable explanation of the result.',
                    },
                    lockedUntil: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Time until which further authentication attempts are blocked.',
                    },
                  },
                  required: ['code', 'message', 'lockedUntil'],
                  description: 'Error details returned when the operation fails.',
                },
              },
              required: ['error'],
            },
          },
        },
      },
      '503': {
        description: 'Service unavailable.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Service unavailable.',
                code: 'service-unavailable',
                status: 503,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
