// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/admin/teams/{teamId}/2fa',
  audience: 'internal',
  auth: 'bearer',
  operation: {
    operationId: 'postAdminTeamsTeamId2fa',
    summary: "Set a team's two-factor requirement",
    description:
      'Enables or disables the requirement for members of the specified team to use two-factor authentication.',
    tags: ['Administration'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              required: {
                type: 'boolean',
              },
            },
            required: ['required'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  type: 'boolean',
                  description: 'Whether the operation succeeded.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team.',
                },
                twoFactorRequired: {
                  description: 'Whether two-factor authentication is required.',
                },
              },
              required: ['ok', 'teamId', 'twoFactorRequired'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '503': {
        description: 'Service unavailable.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Service unavailable.',
                code: 'service-unavailable',
                status: 503,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
