// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/2fa/disable',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'disableTwoFactor',
    summary: 'Disable two-factor authentication',
    description:
      'Disables two-factor authentication for the current user after verifying their password and authenticator code. Rejected when an administrator or team requires it.',
    tags: ['Two-factor authentication'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              password: {
                type: 'string',
                description: 'Password used to authenticate the account.',
              },
              token: {
                type: 'string',
                minLength: 6,
                maxLength: 6,
              },
            },
            required: ['password', 'token'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    error: {
                      type: 'object',
                      properties: {
                        code: {
                          type: 'string',
                        },
                        message: {
                          type: 'string',
                          description: 'Human-readable explanation of the result.',
                        },
                        lockedUntil: {
                          type: 'string',
                          format: 'date-time',
                          description:
                            'Time until which further authentication attempts are blocked.',
                        },
                      },
                      required: ['code', 'message', 'lockedUntil'],
                      description: 'Error details returned when the operation fails.',
                    },
                  },
                  required: ['error'],
                },
                {
                  type: 'object',
                  properties: {
                    ok: {
                      type: 'boolean',
                      description: 'Whether the operation succeeded.',
                    },
                  },
                  required: ['ok'],
                },
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '403': {
        description: 'Forbidden.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Forbidden.',
                code: 'forbidden',
                status: 403,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '429': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                error: {
                  type: 'object',
                  properties: {
                    code: {
                      type: 'string',
                    },
                    message: {
                      type: 'string',
                      description: 'Human-readable explanation of the result.',
                    },
                    lockedUntil: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Time until which further authentication attempts are blocked.',
                    },
                  },
                  required: ['code', 'message', 'lockedUntil'],
                  description: 'Error details returned when the operation fails.',
                },
              },
              required: ['error'],
            },
          },
        },
      },
      '503': {
        description: 'Service unavailable.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Service unavailable.',
                code: 'service-unavailable',
                status: 503,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
