// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/pixels/{pixelId}/shares',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getPixelShares',
    summary: 'List shares for a tracking pixel',
    description: 'Returns a paginated list of shares for the specified tracking pixel.',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the tracking pixel.',
      },
      {
        name: 'path',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page URL path.',
      },
      {
        name: 'referrer',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by referring URL.',
      },
      {
        name: 'title',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page title.',
      },
      {
        name: 'query',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by page URL query string.',
      },
      {
        name: 'os',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Operating system used by the visitor.',
      },
      {
        name: 'browser',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Browser used by the visitor.',
      },
      {
        name: 'device',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Device category used by the visitor.',
      },
      {
        name: 'country',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Country code of the visitor.',
      },
      {
        name: 'region',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Region or subdivision of the visitor.',
      },
      {
        name: 'city',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'City of the visitor.',
      },
      {
        name: 'tag',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Tag attached to the tracked activity.',
      },
      {
        name: 'hostname',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Hostname on which the activity occurred.',
      },
      {
        name: 'distinctId',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Custom identifier assigned to the visitor.',
      },
      {
        name: 'language',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Preferred language reported by the visitor browser.',
      },
      {
        name: 'event',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Filter by custom event name.',
      },
      {
        name: 'utmSource',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign source.',
      },
      {
        name: 'utmMedium',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign medium.',
      },
      {
        name: 'utmCampaign',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign name.',
      },
      {
        name: 'utmContent',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign content.',
      },
      {
        name: 'utmTerm',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'UTM campaign search term.',
      },
      {
        name: 'excludeBounce',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Set a non-empty value to exclude visits with only one pageview.',
      },
      {
        name: 'segment',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
        description: 'ID of a saved segment used to filter results.',
      },
      {
        name: 'cohort',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          format: 'uuid',
        },
        description: 'ID of a saved cohort used to filter visitors.',
      },
      {
        name: 'eventType',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Event type: 1 for a pageview or 2 for a custom event.',
      },
      {
        name: 'match',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['all', 'any'],
        },
        description: 'Whether records must match all filters or any filter.',
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Page number, starting at 1.',
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Number of results per page.',
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Maximum number of results to include.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    data: {
                      description: 'Data returned by the operation.',
                    },
                    count: {
                      description: 'Number of matching records.',
                    },
                    page: {
                      type: 'number',
                      description: 'Page number, starting at 1.',
                    },
                    pageSize: {
                      type: 'number',
                      description: 'Number of results per page.',
                    },
                    orderBy: {
                      type: 'string',
                      description: 'Field to sort the results by.',
                    },
                    search: {
                      type: 'string',
                      description: 'Search text used to filter results.',
                    },
                  },
                  required: ['data', 'count', 'page', 'pageSize', 'orderBy', 'search'],
                },
                {
                  type: 'object',
                  properties: {
                    data: {
                      type: 'array',
                      items: {},
                      description: 'Data returned by the operation.',
                    },
                    count: {
                      type: 'number',
                      description: 'Number of matching records.',
                    },
                    page: {
                      type: 'number',
                      description: 'Page number, starting at 1.',
                    },
                    pageSize: {
                      type: 'number',
                      description: 'Number of results per page.',
                    },
                  },
                  required: ['data', 'count', 'page', 'pageSize'],
                },
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/pixels/{pixelId}/shares',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createPixelShare',
    summary: 'Create a share for a tracking pixel',
    description: 'Creates a named share for the specified tracking pixel with optional parameters.',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the tracking pixel.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 200,
                description: 'Display name of the resource.',
              },
              parameters: {
                description: 'Configuration parameters for the resource.',
              },
            },
            required: ['name'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
