// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/teams',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getTeams',
    summary: 'List my teams',
    description:
      'Returns a paginated list of teams the current user belongs to, with sorting options.',
    tags: ['Teams'],
    parameters: [
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Page number, starting at 1.',
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Number of results per page.',
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Maximum number of results to include.',
      },
      {
        name: 'orderBy',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Field to sort the results by.',
      },
      {
        name: 'sortDescending',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
          enum: ['true', 'false'],
        },
        description: 'Whether to sort results in descending order.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  type: 'array',
                  items: {
                    type: 'object',
                    properties: {
                      id: {
                        type: 'string',
                        description: 'Unique identifier of the resource.',
                      },
                      createdAt: {
                        type: 'string',
                        format: 'date-time',
                        description: 'Date and time the record was created.',
                      },
                      updatedAt: {
                        type: 'string',
                        format: 'date-time',
                        description: 'Date and time the record was last updated.',
                      },
                      logoUrl: {
                        type: 'string',
                        description: 'URL of the logo image.',
                      },
                      twoFactorRequired: {
                        type: 'boolean',
                        description: 'Whether two-factor authentication is required.',
                      },
                      deletedAt: {
                        type: 'string',
                        format: 'date-time',
                        description: 'Date and time the record was deleted, if applicable.',
                      },
                      name: {
                        type: 'string',
                        description: 'Display name of the resource.',
                      },
                      accessCode: {
                        type: 'string',
                        description: 'Code used to join the team.',
                      },
                    },
                    required: [
                      'id',
                      'createdAt',
                      'updatedAt',
                      'logoUrl',
                      'twoFactorRequired',
                      'deletedAt',
                      'name',
                      'accessCode',
                    ],
                  },
                  description: 'Data returned by the operation.',
                },
                count: {
                  type: 'number',
                  description: 'Number of matching records.',
                },
                page: {
                  type: 'number',
                  description: 'Page number, starting at 1.',
                },
                pageSize: {
                  type: 'number',
                  description: 'Number of results per page.',
                },
                orderBy: {
                  type: 'string',
                  description: 'Field to sort the results by.',
                },
                sortDescending: {
                  type: 'boolean',
                  description: 'Whether to sort results in descending order.',
                },
                search: {
                  type: 'string',
                  description: 'Search text used to filter results.',
                },
                isCapped: {
                  type: 'boolean',
                  description: 'Whether the results were truncated by the maximum result limit.',
                },
              },
              required: ['data', 'count', 'page', 'pageSize'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/teams',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createTeam',
    summary: 'Create a team',
    description:
      'Creates a team with an access code and an owner. Administrators can specify a different user as the owner.',
    tags: ['Teams'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 50,
                description: 'Display name of the resource.',
              },
              ownerId: {
                type: 'string',
                format: 'uuid',
              },
            },
            required: ['name'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
