// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/teams/{teamId}/users/{userId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteTeamUser',
    summary: 'Remove a team member',
    description:
      "Removes a user's membership from the specified team, subject to team role and ownership restrictions.",
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/teams/{teamId}/users/{userId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getTeamUser',
    summary: 'Get a team member',
    description: "Returns the specified user's membership details for a team.",
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                role: {
                  type: 'string',
                  description: 'Permission role assigned to the user.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team.',
                },
              },
              required: ['id', 'userId', 'createdAt', 'updatedAt', 'role', 'teamId'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/teams/{teamId}/users/{userId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updateTeamUser',
    summary: "Change a team member's role",
    description:
      "Updates a user's role in the specified team, subject to the caller's role and permissions.",
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              role: {
                type: 'string',
                enum: ['team-member', 'team-view-only', 'team-manager'],
                description: 'Permission role assigned to the user.',
              },
            },
            required: ['role'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
