// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/recorder',
  audience: 'collect',
  auth: 'none',
  operation: {
    operationId: 'getWebsiteRecorderConfig',
    summary: 'Get website recording settings',
    description:
      'Returns public replay and heatmap settings, including sampling, masking, and duration limits. Returns disabled status when recording is unavailable.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    enabled: {
                      type: 'boolean',
                    },
                  },
                  required: ['enabled'],
                },
                {
                  type: 'object',
                  properties: {
                    enabled: {
                      type: 'boolean',
                    },
                    replayEnabled: {
                      type: 'boolean',
                      description: 'Whether session replay recording is enabled.',
                    },
                    heatmapEnabled: {
                      type: 'boolean',
                      description: 'Whether heatmap recording is enabled.',
                    },
                    sampleRate: {
                      type: 'number',
                      description: 'Fraction of sessions to record for replay, from 0 to 1.',
                    },
                    heatmapSampleRate: {
                      type: 'number',
                      description: 'Fraction of sessions to record for heatmaps, from 0 to 1.',
                    },
                    maskLevel: {
                      anyOf: [
                        {
                          const: 'strict',
                        },
                        {
                          const: 'moderate',
                        },
                      ],
                      description:
                        'Privacy masking level used by the recorder: strict or moderate.',
                    },
                    maxDuration: {
                      type: 'number',
                    },
                    blockSelector: {
                      type: 'string',
                      description: 'CSS selector for elements excluded from recordings.',
                    },
                  },
                  required: [
                    'enabled',
                    'replayEnabled',
                    'heatmapEnabled',
                    'sampleRate',
                    'heatmapSampleRate',
                    'maskLevel',
                    'maxDuration',
                    'blockSelector',
                  ],
                },
              ],
            },
          },
        },
      },
      'function toString() { [native code] }': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
