// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/admin/users/{userId}/2fa',
  audience: 'internal',
  auth: 'bearer',
  operation: {
    operationId: 'deleteAdminUsersUserId2fa',
    summary: "Reset a user's two-factor authentication",
    description:
      "Removes the specified user's authenticator setup, backup codes, used-code history, and failed-attempt limits so they can set up authentication again.",
    tags: ['Administration'],
    parameters: [
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  type: 'boolean',
                  description: 'Whether the operation succeeded.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                reset: {
                  type: 'object',
                  properties: {
                    twoFactorAuth: {
                      type: 'number',
                    },
                    backupCodes: {
                      type: 'number',
                      description: 'Single-use backup codes for two-factor authentication.',
                    },
                    otpUsed: {
                      type: 'number',
                    },
                    rateLimit: {
                      type: 'number',
                    },
                  },
                  required: ['twoFactorAuth', 'backupCodes', 'otpUsed', 'rateLimit'],
                },
              },
              required: ['ok', 'userId', 'reset'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/admin/users/{userId}/2fa',
  audience: 'internal',
  auth: 'bearer',
  operation: {
    operationId: 'getAdminUsersUserId2fa',
    summary: "Get a user's two-factor status",
    description: 'Returns whether two-factor authentication is enabled for the specified user.',
    tags: ['Administration'],
    parameters: [
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                isEnabled: {
                  type: 'boolean',
                  description: 'Whether two-factor authentication is enabled.',
                },
              },
              required: ['isEnabled'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/admin/users/{userId}/2fa',
  audience: 'internal',
  auth: 'bearer',
  operation: {
    operationId: 'postAdminUsersUserId2fa',
    summary: "Set a user's two-factor requirement",
    description:
      'Enables or disables the requirement for the specified user to set up two-factor authentication.',
    tags: ['Administration'],
    parameters: [
      {
        name: 'userId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated user.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              required: {
                type: 'boolean',
              },
            },
            required: ['required'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  type: 'boolean',
                  description: 'Whether the operation succeeded.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                twoFactorRequired: {
                  description: 'Whether two-factor authentication is required.',
                },
              },
              required: ['ok', 'userId', 'twoFactorRequired'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '503': {
        description: 'Service unavailable.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Service unavailable.',
                code: 'service-unavailable',
                status: 503,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
