// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/websites/{websiteId}/annotations/{annotationId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteWebsiteAnnotation',
    summary: 'Delete a website annotation',
    description: 'Deletes the specified dated note from the website.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'annotationId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the annotation.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/annotations/{annotationId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteAnnotation',
    summary: 'Get a website annotation',
    description: 'Returns the date, all-day setting, and note for a specific website annotation.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'annotationId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the annotation.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                websiteId: {
                  type: 'string',
                  description: 'ID of the website.',
                },
                date: {
                  type: 'string',
                  format: 'date-time',
                },
                allDay: {
                  type: 'boolean',
                  description: 'Whether the annotation applies to the entire day.',
                },
                note: {
                  type: 'string',
                  description: 'Text of the annotation.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'websiteId',
                'date',
                'allDay',
                'note',
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/websites/{websiteId}/annotations/{annotationId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updateWebsiteAnnotation',
    summary: 'Update a website annotation',
    description: 'Changes the date, all-day setting, and note for a website annotation.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'annotationId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the annotation.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              date: {
                type: 'string',
                format: 'date-time',
              },
              allDay: {
                type: 'boolean',
                description: 'Whether the annotation applies to the entire day.',
              },
              note: {
                type: 'string',
                minLength: 1,
                maxLength: 500,
                description: 'Text of the annotation.',
              },
            },
            required: ['date', 'note'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                websiteId: {
                  type: 'string',
                  description: 'ID of the website.',
                },
                date: {
                  type: 'string',
                  format: 'date-time',
                },
                allDay: {
                  type: 'boolean',
                  description: 'Whether the annotation applies to the entire day.',
                },
                note: {
                  type: 'string',
                  description: 'Text of the annotation.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'websiteId',
                'date',
                'allDay',
                'note',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
