// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/teams/{teamId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteTeam',
    summary: 'Delete a team',
    description: "Deletes the specified team after checking the caller's permission to remove it.",
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/teams/{teamId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getTeam',
    summary: 'Get a team',
    description: "Returns the specified team's details, including its members.",
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                logoUrl: {
                  type: 'string',
                  description: 'URL of the logo image.',
                },
                twoFactorRequired: {
                  type: 'boolean',
                  description: 'Whether two-factor authentication is required.',
                },
                deletedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was deleted, if applicable.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                accessCode: {
                  type: 'string',
                  description: 'Code used to join the team.',
                },
              },
              required: [
                'id',
                'createdAt',
                'updatedAt',
                'logoUrl',
                'twoFactorRequired',
                'deletedAt',
                'name',
                'accessCode',
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/teams/{teamId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updateTeam',
    summary: 'Update a team',
    description: "Updates the specified team's name or access code.",
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 50,
                description: 'Display name of the resource.',
              },
              accessCode: {
                description: 'Code used to join the team.',
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
