// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/share',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createShare',
    summary: 'Create a share',
    description:
      'Creates a named share for a website, board, link, or pixel with parameters and an optional custom slug.',
    tags: ['Shares'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              entityId: {
                type: 'string',
                format: 'uuid',
                description: 'ID of the resource being shared.',
              },
              shareType: {
                description: 'Type of resource made available by the share.',
              },
              name: {
                minimum: 1,
                maximum: 200,
                description: 'Display name of the resource.',
              },
              slug: {
                description: 'URL slug used to access the resource.',
              },
              parameters: {
                description: 'Configuration parameters for the resource.',
              },
            },
            required: ['entityId', 'shareType', 'name', 'parameters'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
