// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/boards/{boardId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deleteBoard',
    summary: 'Delete a board',
    description: "Deletes the specified board after checking the caller's permission to remove it.",
    tags: ['Boards'],
    parameters: [
      {
        name: 'boardId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the board.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/boards/{boardId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getBoard',
    summary: 'Get a board',
    description: 'Returns the specified board and its configuration.',
    tags: ['Boards'],
    parameters: [
      {
        name: 'boardId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the board.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                      description: 'Unique identifier of the resource.',
                    },
                    type: {
                      type: 'string',
                    },
                    name: {
                      type: 'string',
                      description: 'Display name of the resource.',
                    },
                    description: {
                      type: 'string',
                      description: 'Description of the resource.',
                    },
                    parameters: {
                      anyOf: [
                        {
                          type: 'string',
                        },
                        {
                          type: 'number',
                        },
                        {
                          const: false,
                        },
                        {
                          const: true,
                        },
                        {
                          type: 'object',
                          properties: {},
                          additionalProperties: {
                            anyOf: [
                              {
                                type: 'string',
                              },
                              {
                                type: 'number',
                              },
                              {
                                const: false,
                              },
                              {
                                const: true,
                              },
                              {},
                              {
                                type: 'object',
                                properties: {
                                  length: {
                                    type: 'number',
                                  },
                                },
                                required: ['length'],
                              },
                            ],
                          },
                        },
                        {
                          type: 'object',
                          properties: {
                            length: {
                              type: 'number',
                            },
                          },
                          required: ['length'],
                        },
                      ],
                      description: 'Configuration parameters for the resource.',
                    },
                    createdAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was created.',
                    },
                    updatedAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was last updated.',
                    },
                  },
                  required: [
                    'id',
                    'type',
                    'name',
                    'description',
                    'parameters',
                    'createdAt',
                    'updatedAt',
                  ],
                },
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                      description: 'Unique identifier of the resource.',
                    },
                    userId: {
                      type: 'string',
                      description: 'ID of the associated user.',
                    },
                    createdAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was created.',
                    },
                    updatedAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was last updated.',
                    },
                    name: {
                      type: 'string',
                      description: 'Display name of the resource.',
                    },
                    teamId: {
                      type: 'string',
                      description: 'ID of the associated team.',
                    },
                    type: {
                      type: 'string',
                    },
                    description: {
                      type: 'string',
                      description: 'Description of the resource.',
                    },
                    parameters: {
                      anyOf: [
                        {
                          type: 'string',
                        },
                        {
                          type: 'number',
                        },
                        {
                          const: false,
                        },
                        {
                          const: true,
                        },
                        {
                          type: 'object',
                          properties: {},
                          additionalProperties: {
                            anyOf: [
                              {
                                type: 'string',
                              },
                              {
                                type: 'number',
                              },
                              {
                                const: false,
                              },
                              {
                                const: true,
                              },
                              {},
                              {
                                type: 'object',
                                properties: {
                                  length: {
                                    type: 'number',
                                  },
                                },
                                required: ['length'],
                              },
                            ],
                          },
                        },
                        {
                          type: 'object',
                          properties: {
                            length: {
                              type: 'number',
                            },
                          },
                          required: ['length'],
                        },
                      ],
                      description: 'Configuration parameters for the resource.',
                    },
                  },
                  required: [
                    'id',
                    'userId',
                    'createdAt',
                    'updatedAt',
                    'name',
                    'teamId',
                    'type',
                    'description',
                    'parameters',
                  ],
                },
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/boards/{boardId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'updateBoard',
    summary: 'Update a board',
    description:
      "Updates a board's name, description, or configuration and validates the resources and reports it references.",
    tags: ['Boards'],
    parameters: [
      {
        name: 'boardId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the board.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              type: {
                anyOf: [
                  {
                    type: 'string',
                    enum: [],
                  },
                  {
                    const: 'open',
                  },
                ],
              },
              name: {
                minimum: 1,
                maximum: 200,
                description: 'Display name of the resource.',
              },
              description: {
                type: 'string',
                maxLength: 500,
                description: 'Description of the resource.',
              },
              parameters: {
                description: 'Configuration parameters for the resource.',
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team.',
                },
                type: {
                  type: 'string',
                },
                description: {
                  type: 'string',
                  description: 'Description of the resource.',
                },
                parameters: {
                  anyOf: [
                    {
                      type: 'string',
                    },
                    {
                      type: 'number',
                    },
                    {
                      const: false,
                    },
                    {
                      const: true,
                    },
                    {
                      type: 'object',
                      properties: {},
                      additionalProperties: {
                        anyOf: [
                          {
                            type: 'string',
                          },
                          {
                            type: 'number',
                          },
                          {
                            const: false,
                          },
                          {
                            const: true,
                          },
                          {},
                          {
                            type: 'object',
                            properties: {
                              length: {
                                type: 'number',
                              },
                            },
                            required: ['length'],
                          },
                        ],
                      },
                    },
                    {
                      type: 'object',
                      properties: {
                        length: {
                          type: 'number',
                        },
                      },
                      required: ['length'],
                    },
                  ],
                  description: 'Configuration parameters for the resource.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'name',
                'teamId',
                'type',
                'description',
                'parameters',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '500': {
        description: 'Server error.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Server error.',
                code: 'server-error',
                status: 500,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
