// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/websites/{websiteId}/sessions/{sessionId}/properties',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getWebsiteSessionProperties',
    summary: "Get a session's custom properties",
    description:
      'Returns custom property records, data types, and values for the specified website session.',
    tags: ['Websites'],
    parameters: [
      {
        name: 'websiteId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the website.',
      },
      {
        name: 'sessionId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the visitor session.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  websiteId: {
                    type: 'string',
                    description: 'ID of the website.',
                  },
                  sessionId: {
                    type: 'string',
                    description: 'ID of the visitor session.',
                  },
                  dataKey: {
                    type: 'string',
                    description: 'Name of the custom property.',
                  },
                  dataType: {
                    type: 'number',
                    description: 'Data type of the custom property.',
                  },
                  stringValue: {
                    type: 'string',
                    description: 'Custom property value stored as a string.',
                  },
                  numberValue: {
                    type: 'number',
                    description: 'Custom property value stored as a number.',
                  },
                  dateValue: {
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'string',
                        format: 'date-time',
                      },
                    ],
                    description: 'Custom property value stored as a date-time.',
                  },
                  createdAt: {
                    anyOf: [
                      {
                        type: 'string',
                      },
                      {
                        type: 'string',
                        format: 'date-time',
                      },
                    ],
                    description: 'Date and time the record was created.',
                  },
                },
                required: [
                  'websiteId',
                  'sessionId',
                  'dataKey',
                  'dataType',
                  'stringValue',
                  'numberValue',
                  'dateValue',
                  'createdAt',
                ],
              },
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
