// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/me',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'getMe',
    summary: 'Get my authentication details',
    description:
      'Returns the current authentication context, including the authenticated user or share credentials.',
    tags: ['Account'],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                user: {
                  description: 'User associated with the resource.',
                },
                apiKey: {
                  description: 'API key authentication details.',
                },
                authType: {},
                shareToken: {},
              },
              required: ['user', 'apiKey', 'authType', 'shareToken'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
