// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'get',
  path: '/api/teams/{teamId}/users',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getTeamUsers',
    summary: 'List team members',
    description:
      'Returns a paginated list of members of the specified team, including usernames and membership details.',
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
      {
        name: 'page',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Page number, starting at 1.',
      },
      {
        name: 'pageSize',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Number of results per page.',
      },
      {
        name: 'maxResults',
        in: 'query',
        required: false,
        schema: {
          type: 'integer',
          minimum: 1,
        },
        description: 'Maximum number of results to include.',
      },
      {
        name: 'search',
        in: 'query',
        required: false,
        schema: {
          type: 'string',
        },
        description: 'Search text used to filter results.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                data: {
                  description: 'Data returned by the operation.',
                },
                count: {
                  description: 'Number of matching records.',
                },
                page: {
                  type: 'number',
                  description: 'Page number, starting at 1.',
                },
                pageSize: {
                  type: 'number',
                  description: 'Number of results per page.',
                },
                orderBy: {
                  type: 'string',
                  description: 'Field to sort the results by.',
                },
                search: {
                  type: 'string',
                  description: 'Search text used to filter results.',
                },
              },
              required: ['data', 'count', 'page', 'pageSize', 'orderBy', 'search'],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'post',
  path: '/api/teams/{teamId}/users',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'createTeamUser',
    summary: 'Add a team member',
    description: 'Adds an existing user to the specified team with the supplied team role.',
    tags: ['Teams'],
    parameters: [
      {
        name: 'teamId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the associated team.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              userId: {
                type: 'string',
                format: 'uuid',
                description: 'ID of the associated user.',
              },
              role: {
                type: 'string',
                enum: ['team-member', 'team-view-only', 'team-manager'],
                description: 'Permission role assigned to the user.',
              },
            },
            required: ['userId', 'role'],
          },
        },
      },
    },
    responses: {
      '200': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'application/json': {
            schema: {},
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2] as const;
