// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'delete',
  path: '/api/pixels/{pixelId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'deletePixel',
    summary: 'Delete a tracking pixel',
    description:
      "Deletes the specified tracking pixel after checking the caller's permission to remove it.",
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the tracking pixel.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                ok: {
                  const: true,
                  description: 'Whether the operation succeeded.',
                },
              },
              required: ['ok'],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation2 = defineOperation({
  method: 'get',
  path: '/api/pixels/{pixelId}',
  audience: 'public',
  auth: 'bearer-or-share',
  operation: {
    operationId: 'getPixel',
    summary: 'Get a tracking pixel',
    description: 'Returns the specified tracking pixel and its configuration.',
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the tracking pixel.',
      },
    ],
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              anyOf: [
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                      description: 'Unique identifier of the resource.',
                    },
                    name: {
                      type: 'string',
                      description: 'Display name of the resource.',
                    },
                    slug: {
                      type: 'string',
                      description: 'URL slug used to access the resource.',
                    },
                    createdAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was created.',
                    },
                    updatedAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was last updated.',
                    },
                  },
                  required: ['id', 'name', 'slug', 'createdAt', 'updatedAt'],
                },
                {
                  type: 'object',
                  properties: {
                    id: {
                      type: 'string',
                      description: 'Unique identifier of the resource.',
                    },
                    userId: {
                      type: 'string',
                      description: 'ID of the associated user.',
                    },
                    createdAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was created.',
                    },
                    updatedAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was last updated.',
                    },
                    deletedAt: {
                      type: 'string',
                      format: 'date-time',
                      description: 'Date and time the record was deleted, if applicable.',
                    },
                    name: {
                      type: 'string',
                      description: 'Display name of the resource.',
                    },
                    teamId: {
                      type: 'string',
                      description: 'ID of the associated team.',
                    },
                    slug: {
                      type: 'string',
                      description: 'URL slug used to access the resource.',
                    },
                  },
                  required: [
                    'id',
                    'userId',
                    'createdAt',
                    'updatedAt',
                    'deletedAt',
                    'name',
                    'teamId',
                    'slug',
                  ],
                },
              ],
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

const operation3 = defineOperation({
  method: 'post',
  path: '/api/pixels/{pixelId}',
  audience: 'public',
  auth: 'bearer',
  operation: {
    operationId: 'updatePixel',
    summary: 'Update a tracking pixel',
    description: "Updates a tracking pixel's name or slug.",
    tags: ['Pixels'],
    parameters: [
      {
        name: 'pixelId',
        in: 'path',
        required: true,
        schema: {
          type: 'string',
        },
        description: 'ID of the tracking pixel.',
      },
    ],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              name: {
                minimum: 1,
                maximum: 100,
                description: 'Display name of the resource.',
              },
              slug: {
                description: 'URL slug used to access the resource.',
              },
            },
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties: {
                id: {
                  type: 'string',
                  description: 'Unique identifier of the resource.',
                },
                userId: {
                  type: 'string',
                  description: 'ID of the associated user.',
                },
                createdAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was created.',
                },
                updatedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was last updated.',
                },
                deletedAt: {
                  type: 'string',
                  format: 'date-time',
                  description: 'Date and time the record was deleted, if applicable.',
                },
                name: {
                  type: 'string',
                  description: 'Display name of the resource.',
                },
                teamId: {
                  type: 'string',
                  description: 'ID of the associated team.',
                },
                slug: {
                  type: 'string',
                  description: 'URL slug used to access the resource.',
                },
              },
              required: [
                'id',
                'userId',
                'createdAt',
                'updatedAt',
                'deletedAt',
                'name',
                'teamId',
                'slug',
              ],
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '401': {
        description: 'Unauthorized.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Unauthorized.',
                code: 'unauthorized',
                status: 401,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '404': {
        description: 'Not found.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Not found.',
                code: 'not-found',
                status: 404,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '500': {
        description: 'Server error.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Server error.',
                code: 'server-error',
                status: 500,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1, operation2, operation3] as const;
