// Generated by `pnpm openapi:contracts`. Do not edit directly.

import type { ZodOpenApiOperationObject } from 'zod-openapi';
import { defineOperation } from '@/openapi/operation';

const operation1 = defineOperation({
  method: 'post',
  path: '/api/send',
  audience: 'collect',
  auth: 'none',
  operation: {
    operationId: 'send',
    summary: 'Send tracking data',
    description:
      'Collects a pageview, custom event, visitor identification, or performance payload and returns session information and a tracking cache token when accepted.',
    tags: ['Collection'],
    requestBody: {
      required: true,
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              type: {
                type: 'string',
                enum: ['event', 'identify', 'performance'],
              },
              payload: {
                type: 'object',
                properties: {
                  website: {
                    type: 'string',
                    format: 'uuid',
                  },
                  link: {
                    type: 'string',
                    format: 'uuid',
                  },
                  pixel: {
                    type: 'string',
                    format: 'uuid',
                  },
                  data: {
                    description: 'Data returned by the operation.',
                  },
                  hostname: {
                    description: 'Hostname on which the activity occurred.',
                  },
                  language: {
                    type: 'string',
                    maxLength: 35,
                    description: 'Preferred language reported by the visitor browser.',
                  },
                  referrer: {
                    type: 'string',
                    description: 'URL of the referring page.',
                  },
                  screen: {
                    type: 'string',
                    maxLength: 11,
                    description: 'Screen resolution of the visitor device.',
                  },
                  title: {
                    type: 'string',
                    maxLength: 500,
                    description: 'Title of the page.',
                  },
                  url: {
                    type: 'string',
                    description: 'URL associated with the resource.',
                  },
                  name: {
                    description: 'Display name of the resource.',
                  },
                  tag: {
                    description: 'Tag attached to the tracked activity.',
                  },
                  ip: {
                    type: 'string',
                    maxLength: 64,
                  },
                  userAgent: {
                    type: 'string',
                    maxLength: 512,
                  },
                  timestamp: {
                    type: 'integer',
                  },
                  id: {
                    type: 'string',
                    maxLength: 50,
                    description: 'Unique identifier of the resource.',
                  },
                  browser: {
                    type: 'string',
                    maxLength: 20,
                    description: 'Browser used by the visitor.',
                  },
                  os: {
                    type: 'string',
                    maxLength: 20,
                    description: 'Operating system used by the visitor.',
                  },
                  device: {
                    type: 'string',
                    maxLength: 20,
                    description: 'Device category used by the visitor.',
                  },
                  lcp: {
                    type: 'number',
                    minimum: 0,
                    maximum: 60000,
                  },
                  inp: {
                    type: 'number',
                    minimum: 0,
                    maximum: 60000,
                  },
                  cls: {
                    type: 'number',
                    minimum: 0,
                    maximum: 100,
                  },
                  fcp: {
                    type: 'number',
                    minimum: 0,
                    maximum: 60000,
                  },
                  ttfb: {
                    type: 'number',
                    minimum: 0,
                    maximum: 60000,
                  },
                },
              },
            },
            required: ['type', 'payload'],
          },
        },
      },
    },
    responses: {
      '200': {
        description: 'The operation completed successfully.',
        content: {
          'text/plain': {
            schema: {
              type: 'object',
              properties: {
                cache: {},
                sessionId: {
                  description: 'ID of the visitor session.',
                },
                visitId: {
                  description: 'ID of the visit.',
                },
              },
              required: ['cache', 'sessionId', 'visitId'],
            },
          },
        },
      },
      '204': {
        description:
          'Successful response. The response shape is inferred as free-form because the handler does not expose a reusable response schema.',
        content: {
          'text/plain': {
            schema: {
              type: 'string',
            },
          },
        },
      },
      '400': {
        description: 'Bad request.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Bad request.',
                code: 'bad-request',
                status: 400,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
      '500': {
        description: 'Server error.',
        content: {
          'application/json': {
            example: {
              error: {
                message: 'Server error.',
                code: 'server-error',
                status: 500,
              },
            },
            schema: {
              $ref: '#/components/schemas/ApiError',
            },
          },
        },
      },
    },
  } as ZodOpenApiOperationObject,
});

export const operations = [operation1] as const;
